apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartops-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: smartops-backend
  template:
    metadata:
      labels:
        app: smartops-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartops-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartops-frontend
  template:
    metadata:
      labels:
        app: smartops-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
