apiVersion: v1
kind: Service
metadata:
  name: smartops-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: smartops-frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.frontend.port }}
